# Generated by Django 3.1.3 on 2021-06-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210626_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog',
            new_name='blogDescription',
        ),
        migrations.AddField(
            model_name='blog',
            name='blogTitle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
